version: "2.0"

services:

  api:
    container_name: aula_docker_api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: aula_docker_db
    image: postgres:13
    enviroment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
